version: '3'

services:
  app:
    container_name: enviame-test
    build:
      context: .
    ports:
      - "5000:5000"
    command: >
      sh -c "flask db upgrade &&
             flask loadcompanies 20 &&
             flask run"
    env_file: 
      - example.env
    depends_on: 
      db:
        condition: service_healthy
  db:
    image: postgres:13.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: enviame
      POSTGRES_USER: enviame
      POSTGRES_PASSWORD: pass123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enviame"]
      interval: 10s
      timeout: 5s
      retries: 5
