"""company table

Revision ID: 524e683cc410
Revises: 
Create Date: 2021-05-15 13:04:02.280400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524e683cc410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_external_id'), 'company', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_external_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
